# Generated by Django 2.1.7 on 2019-02-17 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(max_length=200)),
                ('notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notice.Notice')),
            ],
        ),
    ]
