# Generated by Django 2.1.7 on 2019-03-01 18:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20190301_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
