# Generated by Django 2.1.7 on 2019-02-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_n_a', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
