# Generated by Django 2.1.7 on 2019-02-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_n_a', '0002_qna_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
