# Generated by Django 2.1.7 on 2019-02-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q_n_a', '0002_auto_20190217_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qna',
            options={'ordering': ('id',)},
        ),
    ]
