# Generated by Django 2.1.7 on 2019-02-21 14:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q_n_a', '0004_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
