# Generated by Django 2.1.7 on 2019-02-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
