# Generated by Django 2.1.7 on 2019-02-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20190215_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
