# Generated by Django 2.1.5 on 2019-03-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20190217_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
