# Generated by Django 2.1.7 on 2019-03-01 16:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20190301_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pic',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
